# Generated by Django 5.0.6 on 2024-06-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('company_code', models.CharField(blank=True, max_length=5, null=True)),
                ('Strength', models.PositiveIntegerField(blank=True)),
                ('Website', models.URLField(blank=True, null=True)),
                ('Create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
